import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Black_Ops_One, Orbitron, Press_Start_2P } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import PageTransition from "@/components/PageTransition";
import { Providers } from "./providers/provider";
import { Toaster } from "sonner";
import { ScrollProvider } from "@/components/ScrollContent";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
});

const blackOpsOne = Black_Ops_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-black-ops",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});

const pressStart2P = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-press-start",
});

export const metadata: Metadata = {
  title: "Projectrix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${plusJakartaSans.variable} ${blackOpsOne.variable} ${orbitron.variable} ${pressStart2P.variable} antialiased`}
      >
        <Providers>
          <ScrollProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <Toaster richColors />
              <PageTransition>{children}</PageTransition>
            </ThemeProvider>
          </ScrollProvider>
        </Providers>
      </body>
    </html>
  );
}