name: Mirror Repository

on:
  push:
    branches: [ main ]  

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to Public Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:geo-hue/projectrix.git
          ssh_private_key:
            ${{ secrets.MIRRORING_SSH_KEY }}